cask_args appdir: "/Applications"
tap "homebrew/cask"

brew "zsh"
brew "stow"
brew "neovim"
brew "tmux"
brew "starship"
brew "nvm"

cask "font-jetbrains-mono-nerd-font"
cask "alacritty"
cask "docker"
cask "google-chrome"
cask "firefox"
cask "discord"
cask "spotify"
