format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character\
"""
add_newline = false

[directory]
style = 'blue'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([$ahead_behind]($style) )'
style = 'cyan'

[aws]
disabled = true
