cask_args appdir: "/Applications"
tap "homebrew/cask"

brew "nushell" # Shell
brew "unzip" # Unzipping library
brew "chezmoi" # Dotfiles manager
brew "neovim" # Code editor
brew "starship" # Prompt
brew "nvm" # Node version manager
brew "ripgrep" # For live grep through repo in neovim

cask "font-jetbrains-mono-nerd-font"
cask "orbstack" # Container manager
cask "google-chrome"
cask "firefox"
cask "discord"
cask "spotify"
cask "wezterm" # Terminal

