# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]

[env]
# Note that some xterm terminfo databases don't declare support for italics.
# You can verify this by checking for the presence of `smso` and `sitm` in
# `infocmp xterm-256color`.
TERM="xterm-256color"

[window]
dimensions={columns=160,lines=80}
padding={x=4,y=4}
decorations="Buttonless"
startup_mode="Maximized"
dynamic_title=true
option_as_alt="Both"

[font]
normal={family="JetBrainsMono Nerd Font", style="Regular"}

[colors]
draw_bold_text_with_bright_colors=true

[debug]
render_timer=false

[selection]
semantic_escape_chars=",│`|:\"' ()[]{}<>"

[cursor]
style="Block"
