# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
# Note that some xterm terminfo databases don't declare support for italics.
# You can verify this by checking for the presence of `smso` and `sitm` in
# `infocmp xterm-256color`.
TERM="xterm-256color"

[window]
dimensions={columns=160,lines=80}
padding={x=4,y=4}
decorations="Buttonless"
startup_mode="Maximized"
dynamic_title=true
option_as_alt="Both"

[font]
normal={family="JetBrainsMono Nerd Font", style="Regular"}

[colors]
draw_bold_text_with_bright_colors=true

[colors.primary]
background='0x1E1D2F'
foreground='0xD9E0EE'

[colors.cursor]
text='0x1E1D2F'
cursor='0xF5E0DC'

[colors.normal]
black='0x6E6C7E'
red='0xF28FAD'
green='0xABE9B3'
yellow='0xFAE3B0'
blue='0x96CDFB'
magenta='0xF5C2E7'
cyan='0x89DCEB'
white='0xD9E0EE'

[colors.bright]
black='0x988BA2'
red='0xF28FAD'
green='0xABE9B3'
yellow='0xFAE3B0'
blue='0x96CDFB'
magenta='0xF5C2E7'
cyan='0x89DCEB'
white='0xD9E0EE'

[debug]
render_timer=false

[selection]
semantic_escape_chars=",│`|:\"' ()[]{}<>"

[cursor]
style="Block"
