vim.lsp.enable("lua_ls")
vim.lsp.enable("roslyn")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("ts_ls")
vim.lsp.enable("eslint")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("marksman")
vim.lsp.enable("gh_actions_ls")
